version: '3.8'

services:
  reporting:
    container_name: reporting
    image: chumaky/postgres_mysql_fdw
    environment:
      POSTGRES_DB: reporting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dreporting_postgresql_bin:/usr/lib/postgresql
      - dreporting_postgresql_data:/var/lib/postgresql/data
      - ./files:/files
    ports:
      - 45432:5432
    networks:
      - db

  consent:
    container_name: consent
    image: postgres:latest
    environment:
      POSTGRES_DB: consent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./consent/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
    ports:
      - 55432:5432
    networks:
      - db



networks:
  db:
    driver: bridge

volumes:
  dreporting_postgresql_data:
  dreporting_postgresql_bin:
  metabase-data:
  mysql-data:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
