version: '3.8'

services:
  consent:
    container_name: consent
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
    ports:
      - 55432:5432
    networks:
      - db

  student:
    image: mysql:8.0
    container_name: student
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Set the root password
      MYSQL_DATABASE: my_database # Name of the database to be created
    ports:
      - "3308:3306"  # Expose MySQL port
    volumes:
      - mysql-data:/var/lib/mysql # Persist MySQL data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql # Mount the seed.sql file for initialization
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  mysql-data:
  pgadmin_root_prefs:
    driver: local
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
